VERSION: test-vqa-1
RUN_MODE: test
DATASET_ROOTPATH: datasets
OUTPATH: outputs

# Workers and batch size
NUM_WORKERS: 8

# Load ckpt
CKPT_FILE: ckpts/vqa-vqav2-base.pkl

CKPT_SAVE_MAP:
  mm_qa_head: mm_qa_head

# Datasets
DATASET_LIST:
  train:
    - 'vqa-vqav2:train'
    - 'vqa-vqav2:val'
  val:
    - 'vqa-vqav2:minival'
  test:
    - 'vqa-vqav2:test'

# Features
IMGFEAT_LIST:
  - coco:butd_res101_36-36_i32w_pyt

# Model Params
PAD_MAX:
  text: 20
  image: 36

TASKS:
  mm:
    - qa