VERSION: test-refcoco-1
RUN_MODE: test
DATASET_ROOTPATH: datasets
OUTPATH: outputs

# Workers and batch size
NUM_WORKERS: 8

# Load ckpt
CKPT_FILE: ckpts/rec-refcoco-base.pkl

CKPT_SAVE_MAP:
  mm_refs_head: mm_refs_head

# Datasets
DATASET_LIST:
  train:
    - refcoco:train
  val:
    - refcoco:val
  test:
    # - refcoco:val
    # - refcoco:testA
    - refcoco:testB

# Features
IMGFEAT_LIST:
  - coco:butd_res101_36-36_i32w_pyt

# Refs Params
BBOX_NORM: True
OVERLAP_THRESHOLD: 0.5

# Model Params
PAD_MAX:
  text: 20
  image: 36

TASKS:
  mm:
    - refs-rank
    - refs-reg